
### produits

GET https://127.0.0.1:8000/api/produits
Accept: application/json

### categories

GET https://127.0.0.1:8000/api/cats
Accept: application/json

### sous-categories

GET https://127.0.0.1:8000/api/scats
Accept: application/json


### sous-categories selon l'id cat

GET https://127.0.0.1:8000/api/scats?cat.id=1
Accept: application/json

### produits selon l'id sous-cat

GET https://127.0.0.1:8000/api/produits?scat.id=3
Accept: application/json


### tests

POST https://127.0.0.1:8000/api/produits
Content-Type: application/json

{ 
    "id": 3,
    "libelle": "GPU qui envoie",
    "prix_vente_ht": "399.00",
    "description": "GPU qui envoie un max jusqu'en 4k",
    "scat_id": 3,
    "scat": "\/api\/scats\/3",
    "fabricant": "\/api\/fabricants\/1",
    "imgProd": "powercolor-radeon-rx-6700-xt-fighter-12gb-gddr6.jpg",
    "scatId": 3
}

###

DELETE https://127.0.0.1:8000/api/produits/9
Content-Type: application/json

###

PATCH https://127.0.0.1:8000/api/produits/10
Content-Type: application/merge-patch+json
Accept: application/json

{ 
    "libelle": "test_patch",
}

###

PUT https://127.0.0.1:8000/api/produits/10
Content-Type: application/merge-patch+json
Accept: application/json

{ 
    "libelle": "test_put",
    "prix_vente_ht": "250.00",
    "description": "AMD RYZEN 7600X Processeur 6 coeurs, 4.70 GHz, 32 Mo, AMD Zen 4, TDP 105 Watts, socket AM5, version bo\u00eete sans ventilateur",
    "scat_id": 4,
    "scat": "\/api\/scats\/4",
    "fabricant": "\/api\/fabricants\/1",
    "imgProd": "amd-ryzen-5-7600x-boxed.jpg",
    "prixAchatFourn": "200.00",
    "prixVenteHt": "250.00",
    "scatId": 4
}

